services:
  - type: web
    name: wa-cloud-sender-seva
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: ADMIN_EMAIL
        value: sachinbamniya0143@gmail.com
      - key: ADMIN_PHONE
        value: +919174406375
      - key: ADMIN_WHATSAPP
        value: 919174406375
      - key: CORS_ORIGIN
        value: "*"
    autoDeploy: true
